Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -60,30 +60,37 @@ jobs:
         run: ./gradlew assembleRelease -Pandroid.injected.signing.store.file=keystore-project.jks -Pandroid.injected.signing.store.password=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.ANDROID_KEY_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.ANDROID_KEY_PASSWORD }}
         env:
           ACTIONS_STEP_DEBUG: true
-
-
-
+      
       # Extract package name from AndroidManifest.xml
       - name: Extract Package Name
         id: extract_package_name
         run: |
-          PACKAGE_NAME=$(grep 'package=' app/src/main/AndroidManifest.xml | sed -E 's/.*package="([^"]+)".*/\1/')
-          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
+          if [ -f app/src/main/AndroidManifest.xml ]; then
+            PACKAGE_NAME=$(grep -oP '(?<=<manifest[^>]*package=")[^"]*' app/src/main/AndroidManifest.xml)
+            if [ -z "$PACKAGE_NAME" ]; then
+              echo "Package name not found in AndroidManifest.xml"
+              exit 1
+            fi
+            echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
+          else
+            echo "AndroidManifest.xml not found"
+            exit 1
+          fi
 
       # Rename Debug APK
       - name: Rename Debug APK
         run: |
-          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/${{ env.PACKAGE_NAME }}-debug.apk
+          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/${{ env.PACKAGE_NAME }}-${{ github.ref_name }}-debug.apk
 
       # Rename Release APK
       - name: Rename Release APK
         run: |
-          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/${{ env.PACKAGE_NAME }}-release.apk
+          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/${{ env.PACKAGE_NAME }}-${{ github.ref_name }}-release.apk
 
       # Create GitHub Release
       - name: Create GitHub Release
         id: create_release
-        uses: actions/create-release@v1
+        uses: actions/create-release@v1.1.0
         with:
           tag_name: ${{ github.ref_name }} # Use the pushed tag as the release tag
           release_name: "Release ${{ github.ref_name }}"
